local M = {}

---@param colors GruvboxDark | GruvboxLight
---@param config GruvboxConfig
---@return table<string, vim.api.keyset.highlight>
M.get = function(colors, config)
    ---@type vim.api.keyset.highlight
    local groups = {
        -- Base
        ColorColumn = { bg = colors.bg1 },
        Conceal = { fg = colors.blue },
        CurSearch = { fg = colors.bg0, bg = colors.orange },
        Cursor = { reverse = true },
        lCursor = { reverse = true },
        CursorColumn = { bg = colors.bg1 },
        CursorLine = { bg = colors.bg1 },
        Directory = { fg = colors.green, bold = config.bold },
        DiffAdd = { bg = colors.green },
        DiffChange = { bg = colors.aqua },
        DiffDelete = { bg = colors.red },
        DiffText = { bg = colors.yellow, fg = colors.bg0 },
        EndOfBuffer = { fg = colors.bg2 },
        ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        WinSeparator = { fg = colors.bg3, bg = config.transparent_mode and colors.none or colors.bg0 },
        Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
        FoldColumn = { fg = colors.gray, bg = config.transparent_mode and colors.none or colors.bg1 },
        SignColumn = { bg = config.transparent_mode and colors.none or colors.bg1 },
        IncSearch = { fg = colors.bg0, bg = colors.orange },
        Substitute = { fg = colors.bg0, bg = colors.orange },
        LineNr = { fg = colors.bg4 },
        CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
        MatchParen = { bg = colors.bg3, bold = config.bold },
        ModeMsg = { fg = colors.yellow, bold = config.bold },
        MoreMsg = { fg = colors.yellow, bold = config.bold },
        NonText = { fg = colors.bg2 },

        Normal = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg0 },
        NormalFloat = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        FloatBorder = { fg = colors.bg3, bg = config.transparent_mode and colors.none or colors.bg1 },
        FloatTitle = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            bold = config.bold,
        },
        NormalNC = {
            fg = colors.fg1,
            bg = config.transparent_mode and colors.none or config.dim_inactive and colors.bg1 or colors.bg0,
        },
        Pmenu = { fg = colors.fg1, bg = colors.bg2 },
        PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
        PmenuSbar = { bg = colors.bg2 },
        PmenuThumb = { bg = colors.bg4 },
        Question = { fg = colors.orange, bold = config.bold },
        QuickFixLine = { fg = colors.purple },
        Search = { fg = colors.bg0, bg = colors.yellow },
        SpecialKey = { fg = colors.fg4 },
        SpellBad = { undercurl = config.undercurl, sp = colors.red },
        SpellCap = { undercurl = config.undercurl, sp = colors.blue },
        SpellLocal = { undercurl = config.undercurl, sp = colors.aqua },
        SpellRare = { undercurl = config.undercurl, sp = colors.purple },
        StatusLine = { fg = colors.fg1, bg = colors.bg2 },
        StatusLineNC = { fg = colors.fg4, bg = colors.bg1 },
        TabLine = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
        Title = { fg = colors.green, bold = config.bold },
        Visual = { bg = colors.bg3, reverse = config.invert_selection },
        VisualNOS = { bg = colors.bg3, reverse = config.invert_selection },
        WarningMsg = { fg = colors.red, bold = config.bold },
        Whitespace = { fg = colors.bg2 },
        WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
        WinBar = { fg = colors.fg1, bg = colors.bg2 },
        WinBarNC = { fg = colors.fg4, bg = colors.bg1 },

        Boolean = { fg = colors.purple },
        Character = { fg = colors.purple },
        Comment = { fg = colors.gray, italic = config.italic.comments },
        Conditional = { fg = colors.red },
        Constant = { fg = colors.purple },
        debugBreakpoint = {
            fg = colors.red,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        debugPC = { bg = colors.green },
        Define = { fg = colors.aqua },
        Delimiter = { fg = colors.orange },
        Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
        Error = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        Exception = { fg = colors.red },
        Float = { fg = colors.purple },
        Function = { fg = colors.green, bold = config.bold },
        Identifier = { fg = colors.blue },
        Include = { fg = colors.aqua },
        Keyword = { fg = colors.red },
        Label = { fg = colors.red },
        Macro = { fg = colors.aqua },
        Number = { fg = colors.purple },
        Operator = { fg = colors.orange, italic = config.italic.operators },
        PreCondit = { fg = colors.aqua },
        PreProc = { fg = colors.aqua },
        Repeat = { fg = colors.red },
        Special = { fg = colors.orange },
        Statement = { fg = colors.red },
        StorageClass = { fg = colors.orange },
        String = { fg = colors.green, italic = config.italic.strings },
        Structure = { fg = colors.aqua },
        Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
        Type = { fg = colors.yellow },
        Typedef = { fg = colors.yellow },
        Underlined = { fg = colors.blue, underline = config.underline },

        -- Diagnostic
        DiagnosticError = { fg = colors.red },
        DiagnosticSignError = {
            fg = colors.red,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        DiagnosticUnderlineError = { undercurl = config.undercurl, sp = colors.red },
        DiagnosticWarn = { fg = colors.yellow },
        DiagnosticSignWarn = {
            fg = colors.yellow,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        DiagnosticUnderlineWarn = { undercurl = config.undercurl, sp = colors.yellow },
        DiagnosticInfo = { fg = colors.blue },
        DiagnosticSignInfo = {
            fg = colors.blue,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        DiagnosticUnderlineInfo = { undercurl = config.undercurl, sp = colors.blue },
        DiagnosticHint = { fg = colors.aqua },
        DiagnosticSignHint = {
            fg = colors.aqua,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        DiagnosticUnderlineHint = { undercurl = config.undercurl, sp = colors.aqua },
        DiagnosticFloatingError = { fg = colors.red },
        DiagnosticFloatingWarn = { fg = colors.orange },
        DiagnosticFloatingInfo = { fg = colors.blue },
        DiagnosticFloatingHint = { fg = colors.aqua },
        DiagnosticVirtualTextError = { fg = colors.red },
        DiagnosticVirtualTextWarn = { fg = colors.yellow },
        DiagnosticVirtualTextInfo = { fg = colors.blue },
        DiagnosticVirtualTextHint = { fg = colors.aqua },
        DiagnosticOk = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },

        --LSP
        LspReferenceRead = { fg = colors.yellow, bold = config.bold },
        LspReferenceText = { fg = colors.yellow, bold = config.bold },
        LspReferenceWrite = { fg = colors.orange, bold = config.bold },
        LspCodeLens = { fg = colors.gray },
        LspSignatureActiveParameter = { fg = colors.bg0, bg = colors.yellow },
        LspInlayHint = { fg = colors.gray },

        -- Netrw
        netrwDir = { fg = colors.aqua },
        netrwClassify = { fg = colors.aqua },
        netrwLink = { fg = colors.gray },
        netrwSymLink = { fg = colors.fg1 },
        netrwExe = { fg = colors.yellow },
        netrwComment = { fg = colors.gray },
        netrwList = { fg = colors.blue },
        netrwHelpCmd = { fg = colors.aqua },
        netrwCmdSep = { fg = colors.fg3 },
        netrwVersion = { fg = colors.green },

        -- Diff
        diffAdded = { fg = colors.green },
        diffRemoved = { fg = colors.red },
        diffChanged = { fg = colors.aqua },
        diffFile = { fg = colors.orange },
        diffNewFile = { fg = colors.yellow },
        diffOldFile = { fg = colors.orange },
        diffLine = { fg = colors.blue },
        diffIndexLine = { fg = colors.aqua },

        -- Gitsigns
        gitcommitSelectedFile = { fg = colors.green },
        gitcommitDiscardedFile = { fg = colors.red },
        GitSignsAdd = { fg = colors.green },
        GitSignsChange = { fg = colors.orange },
        GitSignsDelete = { fg = colors.red },

        -- Nvim-Tree
        NvimTreeSymlink = { fg = colors.neutral_aqua },
        NvimTreeRootFolder = { fg = colors.neutral_purple, bold = config.bold },
        NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = config.bold },
        NvimTreeFileIcon = { fg = colors.fg2 },
        NvimTreeExecFile = { fg = colors.neutral_green, bold = config.bold },
        NvimTreeOpenedFile = { fg = colors.red, bold = config.bold },
        NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = colors.neutral_purple },
        NvimTreeIndentMarker = { fg = colors.bg3 },
        NvimTreeGitDirty = { fg = colors.neutral_yellow },
        NvimTreeGitStaged = { fg = colors.neutral_yellow },
        NvimTreeGitMerge = { fg = colors.neutral_purple },
        NvimTreeGitRenamed = { fg = colors.neutral_purple },
        NvimTreeGitNew = { fg = colors.neutral_yellow },
        NvimTreeGitDeleted = { fg = colors.neutral_red },
        NvimTreeWindowPicker = { bg = colors.aqua },

        -- Startify
        StartifyBracket = { fg = colors.fg3 },
        StartifyFile = { fg = colors.fg1 },
        StartifyNumber = { fg = colors.blue },
        StartifyPath = { fg = colors.gray },
        StartifySlash = { fg = colors.gray },
        StartifySection = { fg = colors.yellow },
        StartifySpecial = { fg = colors.bg2 },
        StartifyHeader = { fg = colors.orange },
        StartifyFooter = { fg = colors.bg2 },
        StartifyVar = { fg = colors.gray },
        StartifySelect = { fg = colors.green, bold = config.bold },

        -- Dirvish
        DirvishPathTail = { fg = colors.aqua },
        DirvishArg = { fg = colors.yellow },

        -- NERDTree
        NERDTreeDir = { fg = colors.aqua },
        NERDTreeDirSlash = { fg = colors.aqua },
        NERDTreeOpenable = { fg = colors.orange },
        NERDTreeClosable = { fg = colors.orange },
        NERDTreeFile = { fg = colors.fg1 },
        NERDTreeExecFile = { fg = colors.yellow },
        NERDTreeUp = { fg = colors.gray },
        NERDTreeCWD = { fg = colors.green },
        NERDTreeHelp = { fg = colors.fg1 },
        NERDTreeToggleOn = { fg = colors.green },
        NERDTreeToggleOff = { fg = colors.red },

        -- CoC
        CocErrorSign = {
            fg = colors.red,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        CocWarningSign = {
            fg = colors.orange,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        CocInfoSign = {
            fg = colors.blue,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        CocHintSign = {
            fg = colors.aqua,
            bg = config.transparent_mode and colors.none or colors.bg1,
            reverse = config.invert_signs,
        },
        CocErrorFloat = { fg = colors.red },
        CocWarningFloat = { fg = colors.orange },
        CocInfoFloat = { fg = colors.blue },
        CocHintFloat = { fg = colors.aqua },
        CocDiagnosticsError = { fg = colors.red },
        CocDiagnosticsWarning = { fg = colors.orange },
        CocDiagnosticsInfo = { fg = colors.blue },
        CocDiagnosticsHint = { fg = colors.aqua },
        CocSelectedText = { fg = colors.red },
        CocMenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
        CocCodeLens = { fg = colors.gray },
        CocErrorHighlight = { undercurl = config.undercurl, sp = colors.red },
        CocWarningHighlight = { undercurl = config.undercurl, sp = colors.orange },
        CocInfoHighlight = { undercurl = config.undercurl, sp = colors.blue },
        CocHintHighlight = { undercurl = config.undercurl, sp = colors.aqua },

        -- Telescope
        TelescopeNormal = { fg = colors.fg1 },
        TelescopeSelection = { fg = colors.orange, bold = config.bold },
        TelescopeSelectionCaret = { fg = colors.red },
        TelescopeMultiSelection = { fg = colors.gray },
        TelescopeBorder = { fg = colors.fg1 },
        TelescopePromptBorder = { fg = colors.fg1 },
        TelescopeResultsBorder = { fg = colors.fg1 },
        TelescopePreviewBorder = { fg = colors.fg1 },
        TelescopeMatching = { fg = colors.blue },
        TelescopePromptPrefix = { fg = colors.red },
        TelescopePrompt = { fg = colors.fg1 },

        -- Cmp
        CmpItemAbbr = { fg = colors.fg0 },
        CmpItemAbbrDeprecated = { fg = colors.fg1 },
        CmpItemAbbrMatch = { fg = colors.blue, bold = config.bold },
        CmpItemAbbrMatchFuzzy = { undercurl = config.undercurl, sp = colors.blue },
        CmpItemMenu = { fg = colors.gray },
        CmpItemKindText = { fg = colors.orange },
        CmpItemKindVariable = { fg = colors.orange },
        CmpItemKindMethod = { fg = colors.blue },
        CmpItemKindFunction = { fg = colors.blue },
        CmpItemKindConstructor = { fg = colors.yellow },
        CmpItemKindUnit = { fg = colors.blue },
        CmpItemKindField = { fg = colors.blue },
        CmpItemKindClass = { fg = colors.yellow },
        CmpItemKindInterface = { fg = colors.yellow },
        CmpItemKindModule = { fg = colors.blue },
        CmpItemKindProperty = { fg = colors.blue },
        CmpItemKindValue = { fg = colors.orange },
        CmpItemKindEnum = { fg = colors.yellow },
        CmpItemKindOperator = { fg = colors.yellow },
        CmpItemKindKeyword = { fg = colors.purple },
        CmpItemKindEvent = { fg = colors.purple },
        CmpItemKindReference = { fg = colors.purple },
        CmpItemKindColor = { fg = colors.purple },
        CmpItemKindSnippet = { fg = colors.green },
        CmpItemKindFile = { fg = colors.blue },
        CmpItemKindFolder = { fg = colors.blue },
        CmpItemKindEnumMember = { fg = colors.aqua },
        CmpItemKindConstant = { fg = colors.orange },
        CmpItemKindStruct = { fg = colors.yellow },
        CmpItemKindTypeParameter = { fg = colors.yellow },

        -- Navic
        NavicIconsFile = { fg = colors.blue },
        NavicIconsModule = { fg = colors.orange },
        NavicIconsNamespace = { fg = colors.blue },
        NavicIconsPackage = { fg = colors.aqua },
        NavicIconsClass = { fg = colors.yellow },
        NavicIconsMethod = { fg = colors.blue },
        NavicIconsProperty = { fg = colors.aqua },
        NavicIconsField = { fg = colors.purple },
        NavicIconsConstructor = { fg = colors.blue },
        NavicIconsEnum = { fg = colors.purple },
        NavicIconsInterface = { fg = colors.green },
        NavicIconsFunction = { fg = colors.blue },
        NavicIconsVariable = { fg = colors.purple },
        NavicIconsConstant = { fg = colors.orange },
        NavicIconsString = { fg = colors.green },
        NavicIconsNumber = { fg = colors.orange },
        NavicIconsBoolean = { fg = colors.orange },
        NavicIconsArray = { fg = colors.orange },
        NavicIconsObject = { fg = colors.orange },
        NavicIconsKey = { fg = colors.aqua },
        NavicIconsNull = { fg = colors.orange },
        NavicIconsEnumMember = { fg = colors.yellow },
        NavicIconsStruct = { fg = colors.purple },
        NavicIconsEvent = { fg = colors.yellow },
        NavicIconsOperator = { fg = colors.red },
        NavicIconsTypeParameter = { fg = colors.red },
        NavicText = { fg = colors.fg1 },
        NavicSeparator = { fg = colors.fg1 },

        -- LSPSaga
        LspSagaCodeActionTitle = { fg = colors.green, bold = config.bold },
        LspSagaCodeActionBorder = { fg = colors.fg1 },
        LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
        LspSagaLspFinderBorder = { fg = colors.fg1 },
        LspSagaAutoPreview = { fg = colors.orange },
        TargetWord = { fg = colors.blue, bold = config.bold },
        FinderSeparator = { fg = colors.aqua },
        LspSagaDefPreviewBorder = { fg = colors.blue },
        LspSagaHoverBorder = { fg = colors.orange },
        LspSagaRenameBorder = { fg = colors.blue },
        LspSagaDiagnosticSource = { fg = colors.orange },
        LspSagaDiagnosticBorder = { fg = colors.purple },
        LspSagaDiagnosticHeader = { fg = colors.green },
        LspSagaSignatureHelpBorder = { fg = colors.green },
        SagaShadow = { fg = colors.bg0 },

        -- Dashboard
        DashboardShortCut = { fg = colors.orange },
        DashboardHeader = { fg = colors.aqua },
        DashboardCenter = { fg = colors.yellow },
        DashboardFooter = { fg = colors.purple, italic = true },

        -- Mason
        MasonHighlight = { fg = colors.aqua },
        MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
        MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
        MasonHighlightSecondary = { fg = colors.yellow },
        MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
        MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
        MasonHeader = { fg = colors.bg0, bg = colors.yellow, bold = true },
        MasonHeaderSecondary = { fg = colors.bg0, bg = colors.blue, bold = true },
        MasonMuted = { fg = colors.fg4 },
        MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
        MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },

        -- Carbon
        CarbonFile = { fg = colors.fg1 },
        CarbonExe = { fg = colors.yellow },
        CarbonSymlink = { fg = colors.aqua },
        CarbonBrokenSymlink = { fg = colors.red },
        CarbonIndicator = { fg = colors.gray },
        CarbonDanger = { fg = colors.red },
        CarbonPending = { fg = colors.yellow },

        -- Noice
        NoiceCursor = { reverse = true },
        NoiceCmdlinePopupBorder = { fg = colors.blue, bg = colors.none },
        NoiceCmdlineIcon = { fg = colors.blue, bg = colors.none },
        NoiceConfirmBorder = { fg = colors.blue, bg = colors.none },
        NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = colors.none },
        NoiceCmdlineIconSearch = { fg = colors.yellow, bg = colors.none },

        -- Notify
        NotifyDEBUGBorder = { fg = colors.blue },
        NotifyDEBUGIcon = { fg = colors.blue },
        NotifyDEBUGTitle = { fg = colors.blue },
        NotifyERRORBorder = { fg = colors.red },
        NotifyERRORIcon = { fg = colors.red },
        NotifyERRORTitle = { fg = colors.red },
        NotifyINFOBorder = { fg = colors.aqua },
        NotifyINFOIcon = { fg = colors.aqua },
        NotifyINFOTitle = { fg = colors.aqua },
        NotifyTRACEBorder = { fg = colors.green },
        NotifyTRACEIcon = { fg = colors.green },
        NotifyTRACETitle = { fg = colors.green },
        NotifyWARNBorder = { fg = colors.yellow },
        NotifyWARNIcon = { fg = colors.yellow },
        NotifyWARNTitle = { fg = colors.yellow },

        -- Illuminate
        IlluminatedWordText = { fg = colors.yellow, bold = config.bold },
        IlluminatedWordRead = { fg = colors.yellow, bold = config.bold },
        IlluminatedWordWrite = { fg = colors.orange, bold = config.bold },

        -- Rainbow Delimiters
        RainbowDelimiterRed = { fg = colors.red },
        RainbowDelimiterOrange = { fg = colors.orange },
        RainbowDelimiterYellow = { fg = colors.yellow },
        RainbowDelimiterGreen = { fg = colors.green },
        RainbowDelimiterBlue = { fg = colors.blue },
        RainbowDelimiterViolet = { fg = colors.purple },
        RainbowDelimiterCyan = { fg = colors.aqua },

        -- DAP
        DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
        DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
        DapUIBreakpointsCurrentLine = { fg = colors.yellow },
        DapUIBreakpointsDisabledLine = { fg = colors.gray },
        DapUIBreakpointsInfo = { fg = colors.aqua },
        DapUIBreakpointsLine = { fg = colors.yellow },
        DapUIBreakpointsPath = { fg = colors.blue },
        DapUICurrentFrameName = { fg = colors.purple },
        DapUIDecoration = { fg = colors.purple },
        DapUIEndofBuffer = { fg = colors.bg2 },
        DapUIFloatBorder = { fg = colors.aqua },
        DapUILineNumber = { fg = colors.yellow },
        DapUIModifiedValue = { fg = colors.red },
        DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
        DapUIRestart = { fg = colors.green, bg = colors.bg1 },
        DapUIScope = { fg = colors.blue },
        DapUISource = { fg = colors.fg1 },
        DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
        DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
        DapUIStop = { fg = colors.red, bg = colors.bg1 },
        DapUIStoppedThread = { fg = colors.blue },
        DapUIThread = { fg = colors.blue },
        DapUIType = { fg = colors.orange },
        DapUIUnavailable = { fg = colors.gray },
        DapUIWatchesEmpty = { fg = colors.gray },
        DapUIWatchesError = { fg = colors.red },
        DapUIWatchesValue = { fg = colors.yellow },
        DapUIWinSelect = { fg = colors.yellow },

        -- NeoGit
        NeogitDiffDelete = { fg = colors.red },
        NeogitDiffAdd = { fg = colors.green },
        NeogitHunkHeader = { fg = colors.fg1, bg = colors.bg2 },
        NeogitHunkHeaderHighlight = { fg = colors.fg4, bg = colors.bg1 },

        -- Diffview
        DiffviewStatusModified = { fg = colors.green, bold = config.bold },
        DiffviewFilePanelInsertions = { fg = colors.green, bold = config.bold },
        DiffviewFilePanelDeletions = { fg = colors.red, bold = config.bold },

        -- Mini.nvim
        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
        MiniClueBorder = { fg = colors.bg3, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniClueDescGroup = { fg = colors.orange },
        MiniClueDescSingle = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniClueNextKey = { fg = colors.aqua },
        MiniClueNextKeyWithPostkeys = { fg = colors.red },
        MiniClueSeparator = { fg = colors.blue },
        MiniClueTitle = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            bold = config.bold,
        },
        MiniCompletionActiveParameter = { underline = true },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDepsChangeAdded = { fg = colors.green },
        MiniDepsChangeRemoved = { fg = colors.red },
        MiniDepsHint = { fg = colors.aqua },
        MiniDepsInfo = { fg = colors.blue },
        MiniDepsMsgBreaking = { fg = colors.yellow },
        MiniDepsPlaceholder = { fg = colors.gray, italic = config.italic.comments },
        MiniDepsTitle = { fg = colors.green, bold = config.bold },
        MiniDepsTitleError = { fg = colors.red },
        MiniDepsTitleSame = { fg = colors.aqua },
        MiniDepsTitleUpdate = { fg = colors.green },
        MiniDiffOverAdd = { fg = colors.green },
        MiniDiffOverChange = { bg = colors.yellow, fg = colors.bg0 },
        MiniDiffOverContext = { fg = colors.aqua },
        MiniDiffOverDelete = { fg = colors.red },
        MiniDiffSignAdd = { fg = colors.green },
        MiniDiffSignChange = { fg = colors.aqua },
        MiniDiffSignDelete = { fg = colors.red },
        MiniFilesBorder = { fg = colors.bg3, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniFilesBorderModified = { fg = colors.orange },
        MiniFilesCursorLine = { bg = colors.bg2 },
        MiniFilesDirectory = { fg = colors.green, bold = config.bold },
        MiniFilesFile = { fg = colors.fg1 },
        MiniFilesNormal = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniFilesTitle = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            bold = config.bold,
        },
        MiniFilesTitleFocused = { fg = colors.orange, bold = config.bold },
        MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
        MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
        MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
        MiniIconsAzure = { fg = colors.blue },
        MiniIconsBlue = { fg = colors.blue },
        MiniIconsCyan = { fg = colors.aqua },
        MiniIconsGreen = { fg = colors.green },
        MiniIconsGrey = { fg = colors.fg0 },
        MiniIconsOrange = { fg = colors.orange },
        MiniIconsPurple = { fg = colors.purple },
        MiniIconsRed = { fg = colors.red },
        MiniIconsYellow = { fg = colors.yellow },
        MiniIndentscopeSymbol = { fg = colors.gray },
        MiniIndentscopeSymbolOff = { fg = colors.yellow },
        MiniJump = { undercurl = config.undercurl, sp = colors.orange },
        MiniJump2dDim = { fg = colors.gray },
        MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
        MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
        MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },
        MiniMapNormal = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniMapSymbolCount = { fg = colors.orange },
        MiniMapSymbolLine = { fg = colors.green, bold = config.bold },
        MiniMapSymbolView = { fg = colors.orange },
        MiniNotifyBorder = { fg = colors.bg3, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniNotifyNormal = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniNotifyTitle = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            bold = config.bold,
        },
        MiniOperatorsExchangeFrom = { fg = colors.bg0, bg = colors.orange },
        MiniPickBorder = { fg = colors.bg3, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniPickBorderBusy = { fg = colors.orange },
        MiniPickBorderText = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            bold = config.bold,
        },
        MiniPickIconDirectory = { fg = colors.green, bold = config.bold },
        MiniPickIconFile = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniPickHeader = { fg = colors.aqua },
        MiniPickMatchCurrent = { bg = colors.bg2 },
        MiniPickMatchMarked = { bg = colors.bg3, reverse = config.invert_selection },
        MiniPickMatchRanges = { fg = colors.aqua },
        MiniPickNormal = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg1 },
        MiniPickPreviewLine = { bg = colors.bg1 },
        MiniPickPreviewRegion = { fg = colors.bg0, bg = colors.orange },
        MiniPickPrompt = { fg = colors.blue },
        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { fg = colors.gray },
        MiniStarterHeader = { fg = colors.green, bold = config.bold },
        MiniStarterInactive = { fg = colors.gray, italic = config.italic.comments },
        MiniStarterItem = { fg = colors.fg1, bg = config.transparent_mode and colors.none or colors.bg0 },
        MiniStarterItemBullet = { fg = colors.orange },
        MiniStarterItemPrefix = { fg = colors.red, bold = config.bold },
        MiniStarterSection = { fg = colors.orange },
        MiniStarterQuery = { fg = colors.yellow, bold = config.bold },
        MiniStatuslineDevinfo = { fg = colors.fg1, bg = colors.bg2 },
        MiniStatuslineFileinfo = { fg = colors.fg1, bg = colors.bg2 },
        MiniStatuslineFilename = { fg = colors.fg4, bg = colors.bg1 },
        MiniStatuslineInactive = { fg = colors.fg4, bg = colors.bg1 },
        MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
        MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
        MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold },
        MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
        MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold },
        MiniSurround = { fg = colors.bg0, bg = colors.orange },
        MiniTablineCurrent = {
            fg = colors.green,
            bg = colors.bg1,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTablineModifiedCurrent = {
            fg = colors.bg1,
            bg = colors.green,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
        MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
        MiniTablineTabpagesection = { fg = colors.bg0, bg = colors.yellow },
        MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
        MiniTestEmphasis = { bold = config.bold },
        MiniTestFail = { fg = colors.red, bold = config.bold },
        MiniTestPass = { fg = colors.green, bold = config.bold },
        MiniTrailspace = { bg = colors.red },

        -- Neo-Tree
        NeoTreeFloatTitle = {
            fg = colors.green,
            bg = config.transparent_mode and colors.none or colors.bg1,
            bold = config.bold,
        },
        NeoTreeFloatNormal = { fg = colors.fg1, bg = colors.bg0 },
        NeoTreeFloatBorder = { fg = colors.bg3, bg = colors.bg0 },
        NeoTreeTitleBar = { fg = colors.bg0, bg = colors.bg3 },
        NeoTreeBufferNumber = { fg = colors.orange },
        NeoTreeMessage = { fg = colors.gray, italic = true },
        NeoTreeDimText = { fg = colors.gray },
        NeoTreeDirectoryIcon = { fg = colors.blue },
        NeoTreeDirectoryName = { fg = colors.fg1 },
        NeoTreeDotfile = { fg = colors.gray },
        NeoTreeHiddenByName = { fg = colors.gray },
        NeoTreeFadeText1 = { fg = colors.bg3 },
        NeoTreeFadeText2 = { fg = colors.bg2 },
        NeoTreeFileIcon = { fg = colors.blue },
        NeoTreeIndentMarker = { fg = colors.bg2 },
        NeoTreeExpander = { fg = colors.bg4 },
        NeoTreeModified = { fg = colors.yellow },
        NeoTreeGitAdded = { fg = colors.green },
        NeoTreeGitDeleted = { fg = colors.red },
        NeoTreeGitModified = { fg = colors.orange },
        NeoTreeGitConflict = { fg = colors.yellow, italic = true, bold = true },
        NeoTreeGitUntracked = { fg = colors.purple, italic = true },
        NeoTreeTabInactive = { fg = colors.gray },
        NeoTreeTabSeparatorActive = { bg = colors.bg1, fg = colors.blue },
        NeoTreeTabSeparatorInactive = { bg = colors.bg0, fg = colors.gray },
        NeoTreeFileStats = { fg = colors.bg3 },
        NeoTreeFileStatsHeader = { fg = colors.bg4, bold = true },

        -- Treesitter
        ["@comment"] = { fg = colors.gray, italic = config.italic.comments },
        ["@none"] = { fg = colors.none, bg = colors.none },
        ["@preproc"] = { fg = colors.aqua },
        ["@define"] = { fg = colors.aqua },
        ["@operator"] = { fg = colors.orange, italic = config.italic.operators },
        ["@punctuation.delimiter"] = { fg = colors.orange },
        ["@punctuation.bracket"] = { fg = colors.orange },
        ["@punctuation.special"] = { fg = colors.orange },
        ["@string"] = { fg = colors.green, italic = config.italic.strings },
        ["@string.regex"] = { fg = colors.green, italic = config.italic.strings },
        ["@string.regexp"] = { fg = colors.green, italic = config.italic.strings },
        ["@string.escape"] = { fg = colors.orange },
        ["@string.special"] = { fg = colors.orange },
        ["@string.special.path"] = { fg = colors.blue, underline = config.underline },
        ["@string.special.symbol"] = { fg = colors.blue },
        ["@string.special.url"] = { fg = colors.blue, underline = config.underline },
        ["@character"] = { fg = colors.purple },
        ["@character.special"] = { fg = colors.orange },
        ["@boolean"] = { fg = colors.purple },
        ["@number"] = { fg = colors.purple },
        ["@number.float"] = { fg = colors.purple },
        ["@float"] = { fg = colors.purple },
        ["@function"] = { fg = colors.green, bold = config.bold },
        ["@function.builtin"] = { fg = colors.orange },
        ["@function.call"] = { fg = colors.green, bold = config.bold },
        ["@function.macro"] = { fg = colors.aqua },
        ["@function.method"] = { fg = colors.green, bold = config.bold },
        ["@method"] = { fg = colors.green, bold = config.bold },
        ["@method.call"] = { fg = colors.green, bold = config.bold },
        ["@constructor"] = { fg = colors.orange },
        ["@parameter"] = { fg = colors.blue },
        ["@keyword"] = { fg = colors.red },
        ["@keyword.conditional"] = { fg = colors.red },
        ["@keyword.debug"] = { fg = colors.orange },
        ["@keyword.directive"] = { fg = colors.aqua },
        ["@keyword.directive.define"] = { fg = colors.aqua },
        ["@keyword.exception"] = { fg = colors.red },
        ["@keyword.function"] = { fg = colors.red },
        ["@keyword.import"] = { fg = colors.aqua },
        ["@keyword.operator"] = { fg = colors.red },
        ["@keyword.repeat"] = { fg = colors.red },
        ["@keyword.return"] = { fg = colors.red },
        ["@keyword.storage"] = { fg = colors.orange },
        ["@conditional"] = { fg = colors.red },
        ["@repeat"] = { fg = colors.red },
        ["@debug"] = { fg = colors.orange },
        ["@label"] = { fg = colors.red },
        ["@include"] = { fg = colors.aqua },
        ["@exception"] = { fg = colors.red },
        ["@type"] = { fg = colors.yellow },
        ["@type.builtin"] = { fg = colors.yellow },
        ["@type.definition"] = { fg = colors.yellow },
        ["@type.qualifier"] = { fg = colors.yellow },
        ["@storageclass"] = { fg = colors.orange },
        ["@attribute"] = { fg = colors.aqua },
        ["@field"] = { fg = colors.blue },
        ["@property"] = { fg = colors.blue },
        ["@variable"] = { fg = colors.fg1 },
        ["@variable.builtin"] = { fg = colors.orange },
        ["@variable.member"] = { fg = colors.blue },
        ["@variable.parameter"] = { fg = colors.blue },
        ["@constant"] = { fg = colors.purple },
        ["@constant.builtin"] = { fg = colors.orange },
        ["@constant.macro"] = { fg = colors.aqua },
        ["@markup"] = { fg = colors.fg1 },
        ["@markup.strong"] = { bold = config.bold },
        ["@markup.italic"] = { italic = config.italic.emphasis },
        ["@markup.underline"] = { underline = config.underline },
        ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
        ["@markup.heading"] = { fg = colors.green, bold = config.bold },
        ["@markup.raw"] = { fg = colors.green, italic = config.italic.strings },
        ["@markup.math"] = { fg = colors.orange },
        ["@markup.environment"] = { fg = colors.aqua },
        ["@markup.environment.name"] = { fg = colors.yellow },
        ["@markup.link"] = { fg = colors.blue, underline = config.underline },
        ["@markup.link.label"] = { fg = colors.orange },
        ["@markup.list"] = { fg = colors.orange },
        ["@markup.list.checked"] = { fg = colors.green },
        ["@markup.list.unchecked"] = { fg = colors.gray },
        ["@comment.todo"] = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
        ["@comment.note"] = { fg = colors.orange },
        ["@comment.warning"] = { fg = colors.red, bold = config.bold },
        ["@comment.error"] = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        ["@diff.plus"] = { fg = colors.green },
        ["@diff.minus"] = { fg = colors.red },
        ["@diff.delta"] = { fg = colors.aqua },
        ["@module"] = { fg = colors.fg1 },
        ["@namespace"] = { fg = colors.fg1 },
        ["@symbol"] = { fg = colors.blue },
        ["@text"] = { fg = colors.fg1 },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { fg = colors.green, bold = config.bold },
        ["@text.literal"] = { fg = colors.green, italic = config.italic.strings },
        ["@text.uri"] = { fg = colors.blue, underline = config.underline },
        ["@text.math"] = { fg = colors.orange },
        ["@text.environment"] = { fg = colors.aqua },
        ["@text.environment.name"] = { fg = colors.yellow },
        ["@text.reference"] = { fg = colors.purple },
        ["@text.todo"] = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
        ["@text.todo.checked"] = { fg = colors.green },
        ["@text.todo.unchecked"] = { fg = colors.gray },
        ["@text.note"] = { fg = colors.orange },
        ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
        ["@text.warning"] = { fg = colors.red, bold = config.bold },
        ["@text.danger"] = { fg = colors.bg0, bg = colors.red, bold = config.bold },
        ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
        ["@text.diff.add"] = { fg = colors.green },
        ["@text.diff.delete"] = { fg = colors.red },
        ["@tag"] = { fg = colors.orange },
        ["@tag.attribute"] = { fg = colors.blue },
        ["@tag.delimiter"] = { fg = colors.orange },
        ["@punctuation"] = { fg = colors.orange },
        ["@macro"] = { fg = colors.aqua },
        ["@structure"] = { fg = colors.aqua },

        -- Semantic Tokens
        ["@lsp.type.class"] = { fg = colors.yellow },
        ["@lsp.type.comment"] = { fg = colors.gray, italic = config.italic.comments },
        ["@lsp.type.decorator"] = { fg = colors.aqua },
        ["@lsp.type.enum"] = { fg = colors.yellow },
        ["@lsp.type.enumMember"] = { fg = colors.purple },
        ["@lsp.type.function"] = { fg = colors.green, bold = config.bold },
        ["@lsp.type.interface"] = { fg = colors.orange },
        ["@lsp.type.macro"] = { fg = colors.aqua },
        ["@lsp.type.method"] = { fg = colors.green, bold = config.bold },
        ["@lsp.type.modifier.java"] = { fg = colors.red },
        ["@lsp.type.namespace"] = { fg = colors.fg1 },
        ["@lsp.type.parameter"] = { fg = colors.blue },
        ["@lsp.type.property"] = { fg = colors.blue },
        ["@lsp.type.struct"] = { fg = colors.yellow },
        ["@lsp.type.type"] = { fg = colors.yellow },
        ["@lsp.type.typeParameter"] = { fg = colors.yellow },
        ["@lsp.type.variable"] = { fg = colors.fg1 },
    }

    if config.group_override then
        for hl, content in pairs(config.group_override) do
            groups[hl] = vim.tbl_extend("force", groups[hl] or {}, content or {})
        end
    end

    return groups
end

return M
