local M = {}

M.get = function(bg)
    local config = require("gruvbox.config").opts
    local palette = require("gruvbox.colors")[bg]

    if config.terminal_colors then
        vim.g.terminal_color_0 = palette.bg0
        vim.g.terminal_color_8 = palette.gray

        vim.g.terminal_color_1 = palette.neutral_red
        vim.g.terminal_color_9 = palette.red

        vim.g.terminal_color_2 = palette.neutral_green
        vim.g.terminal_color_10 = palette.green

        vim.g.terminal_color_3 = palette.neutral_yellow
        vim.g.terminal_color_11 = palette.yellow

        vim.g.terminal_color_4 = palette.neutral_blue
        vim.g.terminal_color_12 = palette.blue

        vim.g.terminal_color_5 = palette.neutral_purple
        vim.g.terminal_color_13 = palette.purple

        vim.g.terminal_color_6 = palette.neutral_aqua
        vim.g.terminal_color_14 = palette.aqua

        vim.g.terminal_color_7 = palette.fg4
        vim.g.terminal_color_15 = palette.fg1
    end

    local groups = {
        -- Gruvbox
        GruvboxFg0 = { fg = palette.fg0 },
        GruvboxFg1 = { fg = palette.fg1 },
        GruvboxFg2 = { fg = palette.fg2 },
        GruvboxFg3 = { fg = palette.fg3 },
        GruvboxFg4 = { fg = palette.fg4 },
        GruvboxGray = { fg = palette.gray },
        GruvboxBg0 = { fg = palette.bg0 },
        GruvboxBg1 = { fg = palette.bg1 },
        GruvboxBg2 = { fg = palette.bg2 },
        GruvboxBg3 = { fg = palette.bg3 },
        GruvboxBg4 = { fg = palette.bg4 },
        GruvboxRed = { fg = palette.red },
        GruvboxRedBold = { fg = palette.red, bold = config.bold },
        GruvboxGreen = { fg = palette.green },
        GruvboxGreenBold = { fg = palette.green, bold = config.bold },
        GruvboxYellow = { fg = palette.yellow },
        GruvboxYellowBold = { fg = palette.yellow, bold = config.bold },
        GruvboxBlue = { fg = palette.blue },
        GruvboxBlueBold = { fg = palette.blue, bold = config.bold },
        GruvboxPurple = { fg = palette.purple },
        GruvboxPurpleBold = { fg = palette.purple, bold = config.bold },
        GruvboxAqua = { fg = palette.aqua },
        GruvboxAquaBold = { fg = palette.aqua, bold = config.bold },
        GruvboxOrange = { fg = palette.orange },
        GruvboxOrangeBold = { fg = palette.orange, bold = config.bold },
        GruvboxRedSign = {
            fg = palette.red,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxGreenSign = {
            fg = palette.green,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxYellowSign = {
            fg = palette.yellow,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxBlueSign = {
            fg = palette.blue,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxPurpleSign = {
            fg = palette.purple,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxAquaSign = {
            fg = palette.aqua,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxOrangeSign = {
            fg = palette.orange,
            bg = config.transparent_mode and "NONE" or palette.bg1,
            reverse = config.invert_signs,
        },
        GruvboxRedUnderline = { undercurl = config.undercurl, sp = palette.red },
        GruvboxGreenUnderline = { undercurl = config.undercurl, sp = palette.green },
        GruvboxYellowUnderline = { undercurl = config.undercurl, sp = palette.yellow },
        GruvboxBlueUnderline = { undercurl = config.undercurl, sp = palette.blue },
        GruvboxPurpleUnderline = { undercurl = config.undercurl, sp = palette.purple },
        GruvboxAquaUnderline = { undercurl = config.undercurl, sp = palette.aqua },
        GruvboxOrangeUnderline = { undercurl = config.undercurl, sp = palette.orange },

        -- Base
        Normal = { fg = palette.fg1, bg = config.transparent_mode and "NONE" or palette.bg0 },
        NormalFloat = { fg = palette.fg1, bg = config.transparent_mode and "NONE" or palette.bg1 },
        NormalNC = config.dim_inactive and { fg = palette.fg0, bg = palette.bg1 } or { link = "Normal" },
        CursorLine = { bg = palette.bg1 },
        CursorColumn = { link = "CursorLine" },
        TabLineFill = { fg = palette.bg4, bg = palette.bg1, reverse = config.invert_tabline },
        TabLineSel = { fg = palette.green, bg = palette.bg1, reverse = config.invert_tabline },
        TabLine = { link = "TabLineFill" },
        MatchParen = { bg = palette.bg3, bold = config.bold },
        ColorColumn = { bg = palette.bg1 },
        Conceal = { fg = palette.blue },
        CursorLineNr = { fg = palette.yellow, bg = palette.bg1 },
        NonText = { link = "GruvboxBg2" },
        SpecialKey = { link = "GruvboxFg4" },
        Visual = { bg = palette.bg3, reverse = config.invert_selection },
        VisualNOS = { link = "Visual" },
        Search = { fg = palette.bg0, bg = palette.yellow },
        IncSearch = { fg = palette.bg0, bg = palette.orange },
        CurSearch = { link = "IncSearch" },
        QuickFixLine = { link = "GruvboxPurple" },
        Underlined = { fg = palette.blue, underline = config.underline },
        StatusLine = { fg = palette.fg1, bg = palette.bg2 },
        StatusLineNC = { fg = palette.fg4, bg = palette.bg1 },
        WinBar = { fg = palette.fg4, bg = palette.bg0 },
        WinBarNC = { fg = palette.fg3, bg = palette.bg1 },
        WinSeparator = { fg = palette.bg3, bg = config.transparent_mode and "NONE" or palette.bg0 },
        WildMenu = { fg = palette.blue, bg = palette.bg2, bold = config.bold },
        Directory = { link = "GruvboxGreenBold" },
        Title = { link = "GruvboxGreenBold" },
        ErrorMsg = { fg = palette.bg0, bg = palette.red, bold = config.bold },
        MoreMsg = { link = "GruvboxYellowBold" },
        ModeMsg = { link = "GruvboxYellowBold" },
        Question = { link = "GruvboxOrangeBold" },
        WarningMsg = { link = "GruvboxRedBold" },
        LineNr = { fg = palette.bg4 },
        SignColumn = { bg = config.transparent_mode and "NONE" or palette.bg1 },
        Folded = { fg = palette.gray, bg = palette.bg1, italic = config.italic.folds },
        FoldColumn = { fg = palette.gray, bg = config.transparent_mode and "NONE" or palette.bg1 },
        Cursor = { reverse = true },
        vCursor = { link = "Cursor" },
        iCursor = { link = "Cursor" },
        lCursor = { link = "Cursor" },
        Special = { link = "GruvboxOrange" },
        Comment = { fg = palette.gray, italic = config.italic.comments },
        Todo = { fg = palette.bg0, bg = palette.yellow, bold = config.bold, italic = config.italic.comments },
        Done = { fg = palette.orange, bold = config.bold, italic = config.italic.comments },
        Error = { fg = palette.bg0, bg = palette.red, bold = config.bold },
        Statement = { link = "GruvboxRed" },
        Conditional = { link = "GruvboxRed" },
        Repeat = { link = "GruvboxRed" },
        Label = { link = "GruvboxRed" },
        Exception = { link = "GruvboxRed" },
        Operator = { fg = palette.orange, italic = config.italic.operators },
        Keyword = { link = "GruvboxRed" },
        Identifier = { link = "GruvboxBlue" },
        Function = { link = "GruvboxGreenBold" },
        PreProc = { link = "GruvboxAqua" },
        Include = { link = "GruvboxAqua" },
        Define = { link = "GruvboxAqua" },
        Macro = { link = "GruvboxAqua" },
        PreCondit = { link = "GruvboxAqua" },
        Constant = { link = "GruvboxPurple" },
        Character = { link = "GruvboxPurple" },
        String = { fg = palette.green, italic = config.italic.strings },
        Boolean = { link = "GruvboxPurple" },
        Number = { link = "GruvboxPurple" },
        Float = { link = "GruvboxPurple" },
        Type = { link = "GruvboxYellow" },
        StorageClass = { link = "GruvboxOrange" },
        Structure = { link = "GruvboxAqua" },
        Typedef = { link = "GruvboxYellow" },
        Pmenu = { fg = palette.fg1, bg = palette.bg2 },
        PmenuSel = { fg = palette.bg2, bg = palette.blue, bold = config.bold },
        PmenuSbar = { bg = palette.bg2 },
        PmenuThumb = { bg = palette.bg4 },
        DiffDelete = { bg = palette.red },
        DiffAdd = { bg = palette.green },
        DiffChange = { bg = palette.aqua },
        DiffText = { bg = palette.yellow, fg = palette.bg0 },
        SpellCap = { link = "GruvboxBlueUnderline" },
        SpellBad = { link = "GruvboxRedUnderline" },
        SpellLocal = { link = "GruvboxAquaUnderline" },
        SpellRare = { link = "GruvboxPurpleUnderline" },
        Whitespace = { fg = palette.bg2 },
        Delimiter = { link = "GruvboxOrange" },
        EndOfBuffer = { link = "NonText" },
        debugPC = { link = "DiffAdd" },
        debugBreakpoint = { link = "GruvboxRedSign" },

        -- Diagnostic
        DiagnosticError = { link = "GruvboxRed" },
        DiagnosticSignError = { link = "GruvboxRedSign" },
        DiagnosticUnderlineError = { link = "GruvboxRedUnderline" },
        DiagnosticWarn = { link = "GruvboxYellow" },
        DiagnosticSignWarn = { link = "GruvboxYellowSign" },
        DiagnosticUnderlineWarn = { link = "GruvboxYellowUnderline" },
        DiagnosticInfo = { link = "GruvboxBlue" },
        DiagnosticSignInfo = { link = "GruvboxBlueSign" },
        DiagnosticUnderlineInfo = { link = "GruvboxBlueUnderline" },
        DiagnosticHint = { link = "GruvboxAqua" },
        DiagnosticSignHint = { link = "GruvboxAquaSign" },
        DiagnosticUnderlineHint = { link = "GruvboxAquaUnderline" },
        DiagnosticFloatingError = { link = "GruvboxRed" },
        DiagnosticFloatingWarn = { link = "GruvboxOrange" },
        DiagnosticFloatingInfo = { link = "GruvboxBlue" },
        DiagnosticFloatingHint = { link = "GruvboxAqua" },
        DiagnosticVirtualTextError = { link = "GruvboxRed" },
        DiagnosticVirtualTextWarn = { link = "GruvboxYellow" },
        DiagnosticVirtualTextInfo = { link = "GruvboxBlue" },
        DiagnosticVirtualTextHint = { link = "GruvboxAqua" },
        DiagnosticOk = { link = "GruvboxGreenSign" },

        --LSP
        LspReferenceRead = { link = "GruvboxYellowBold" },
        LspReferenceText = { link = "GruvboxYellowBold" },
        LspReferenceWrite = { link = "GruvboxOrangeBold" },
        LspCodeLens = { link = "GruvboxGray" },
        LspSignatureActiveParameter = { link = "Search" },
        LspInlayHint = { link = "comment" },

        -- Netrw
        netrwDir = { link = "GruvboxAqua" },
        netrwClassify = { link = "GruvboxAqua" },
        netrwLink = { link = "GruvboxGray" },
        netrwSymLink = { link = "GruvboxFg1" },
        netrwExe = { link = "GruvboxYellow" },
        netrwComment = { link = "GruvboxGray" },
        netrwList = { link = "GruvboxBlue" },
        netrwHelpCmd = { link = "GruvboxAqua" },
        netrwCmdSep = { link = "GruvboxFg3" },
        netrwVersion = { link = "GruvboxGreen" },

        -- Diff
        diffAdded = { link = "DiffAdd" },
        diffRemoved = { link = "DiffDelete" },
        diffChanged = { link = "DiffChange" },
        diffFile = { link = "GruvboxOrange" },
        diffNewFile = { link = "GruvboxYellow" },
        diffOldFile = { link = "GruvboxOrange" },
        diffLine = { link = "GruvboxBlue" },
        diffIndexLine = { link = "diffChanged" },

        -- Gitsigns
        gitcommitSelectedFile = { link = "GruvboxGreen" },
        gitcommitDiscardedFile = { link = "GruvboxRed" },
        GitSignsAdd = { link = "GruvboxGreen" },
        GitSignsChange = { link = "GruvboxOrange" },
        GitSignsDelete = { link = "GruvboxRed" },

        -- Nvim-Tree
        NvimTreeSymlink = { fg = palette.neutral_aqua },
        NvimTreeRootFolder = { fg = palette.neutral_purple, bold = true },
        NvimTreeFolderIcon = { fg = palette.neutral_blue, bold = true },
        NvimTreeFileIcon = { fg = palette.light2 },
        NvimTreeExecFile = { fg = palette.neutral_green, bold = true },
        NvimTreeOpenedFile = { fg = palette.bright_red, bold = true },
        NvimTreeSpecialFile = { fg = palette.neutral_yellow, bold = true, underline = true },
        NvimTreeImageFile = { fg = palette.neutral_purple },
        NvimTreeIndentMarker = { fg = palette.dark3 },
        NvimTreeGitDirty = { fg = palette.neutral_yellow },
        NvimTreeGitStaged = { fg = palette.neutral_yellow },
        NvimTreeGitMerge = { fg = palette.neutral_purple },
        NvimTreeGitRenamed = { fg = palette.neutral_purple },
        NvimTreeGitNew = { fg = palette.neutral_yellow },
        NvimTreeGitDeleted = { fg = palette.neutral_red },
        NvimTreeWindowPicker = { bg = palette.aqua },

        -- Startify
        StartifyBracket = { link = "GruvboxFg3" },
        StartifyFile = { link = "GruvboxFg1" },
        StartifyNumber = { link = "GruvboxBlue" },
        StartifyPath = { link = "GruvboxGray" },
        StartifySlash = { link = "GruvboxGray" },
        StartifySection = { link = "GruvboxYellow" },
        StartifySpecial = { link = "GruvboxBg2" },
        StartifyHeader = { link = "GruvboxOrange" },
        StartifyFooter = { link = "GruvboxBg2" },
        StartifyVar = { link = "StartifyPath" },
        StartifySelect = { link = "Title" },

        -- Dirvish
        DirvishPathTail = { link = "GruvboxAqua" },
        DirvishArg = { link = "GruvboxYellow" },

        -- NERDTree
        NERDTreeDir = { link = "GruvboxAqua" },
        NERDTreeDirSlash = { link = "GruvboxAqua" },
        NERDTreeOpenable = { link = "GruvboxOrange" },
        NERDTreeClosable = { link = "GruvboxOrange" },
        NERDTreeFile = { link = "GruvboxFg1" },
        NERDTreeExecFile = { link = "GruvboxYellow" },
        NERDTreeUp = { link = "GruvboxGray" },
        NERDTreeCWD = { link = "GruvboxGreen" },
        NERDTreeHelp = { link = "GruvboxFg1" },
        NERDTreeToggleOn = { link = "GruvboxGreen" },
        NERDTreeToggleOff = { link = "GruvboxRed" },

        -- CoC
        CocErrorSign = { link = "GruvboxRedSign" },
        CocWarningSign = { link = "GruvboxOrangeSign" },
        CocInfoSign = { link = "GruvboxBlueSign" },
        CocHintSign = { link = "GruvboxAquaSign" },
        CocErrorFloat = { link = "GruvboxRed" },
        CocWarningFloat = { link = "GruvboxOrange" },
        CocInfoFloat = { link = "GruvboxBlue" },
        CocHintFloat = { link = "GruvboxAqua" },
        CocDiagnosticsError = { link = "GruvboxRed" },
        CocDiagnosticsWarning = { link = "GruvboxOrange" },
        CocDiagnosticsInfo = { link = "GruvboxBlue" },
        CocDiagnosticsHint = { link = "GruvboxAqua" },
        CocSelectedText = { link = "GruvboxRed" },
        CocMenuSel = { link = "PmenuSel" },
        CocCodeLens = { link = "GruvboxGray" },
        CocErrorHighlight = { link = "GruvboxRedUnderline" },
        CocWarningHighlight = { link = "GruvboxOrangeUnderline" },
        CocInfoHighlight = { link = "GruvboxBlueUnderline" },
        CocHintHighlight = { link = "GruvboxAquaUnderline" },

        -- Telescope
        TelescopeNormal = { link = "GruvboxFg1" },
        TelescopeSelection = { link = "GruvboxOrangeBold" },
        TelescopeSelectionCaret = { link = "GruvboxRed" },
        TelescopeMultiSelection = { link = "GruvboxGray" },
        TelescopeBorder = { link = "TelescopeNormal" },
        TelescopePromptBorder = { link = "TelescopeNormal" },
        TelescopeResultsBorder = { link = "TelescopeNormal" },
        TelescopePreviewBorder = { link = "TelescopeNormal" },
        TelescopeMatching = { link = "GruvboxBlue" },
        TelescopePromptPrefix = { link = "GruvboxRed" },
        TelescopePrompt = { link = "TelescopeNormal" },

        -- Cmp
        CmpItemAbbr = { link = "GruvboxFg0" },
        CmpItemAbbrDeprecated = { link = "GruvboxFg1" },
        CmpItemAbbrMatch = { link = "GruvboxBlueBold" },
        CmpItemAbbrMatchFuzzy = { link = "GruvboxBlueUnderline" },
        CmpItemMenu = { link = "GruvboxGray" },
        CmpItemKindText = { link = "GruvboxOrange" },
        CmpItemKindVariable = { link = "GruvboxOrange" },
        CmpItemKindMethod = { link = "GruvboxBlue" },
        CmpItemKindFunction = { link = "GruvboxBlue" },
        CmpItemKindConstructor = { link = "GruvboxYellow" },
        CmpItemKindUnit = { link = "GruvboxBlue" },
        CmpItemKindField = { link = "GruvboxBlue" },
        CmpItemKindClass = { link = "GruvboxYellow" },
        CmpItemKindInterface = { link = "GruvboxYellow" },
        CmpItemKindModule = { link = "GruvboxBlue" },
        CmpItemKindProperty = { link = "GruvboxBlue" },
        CmpItemKindValue = { link = "GruvboxOrange" },
        CmpItemKindEnum = { link = "GruvboxYellow" },
        CmpItemKindOperator = { link = "GruvboxYellow" },
        CmpItemKindKeyword = { link = "GruvboxPurple" },
        CmpItemKindEvent = { link = "GruvboxPurple" },
        CmpItemKindReference = { link = "GruvboxPurple" },
        CmpItemKindColor = { link = "GruvboxPurple" },
        CmpItemKindSnippet = { link = "GruvboxGreen" },
        CmpItemKindFile = { link = "GruvboxBlue" },
        CmpItemKindFolder = { link = "GruvboxBlue" },
        CmpItemKindEnumMember = { link = "GruvboxAqua" },
        CmpItemKindConstant = { link = "GruvboxOrange" },
        CmpItemKindStruct = { link = "GruvboxYellow" },
        CmpItemKindTypeParameter = { link = "GruvboxYellow" },

        -- Navic
        NavicIconsFile = { link = "GruvboxBlue" },
        NavicIconsModule = { link = "GruvboxOrange" },
        NavicIconsNamespace = { link = "GruvboxBlue" },
        NavicIconsPackage = { link = "GruvboxAqua" },
        NavicIconsClass = { link = "GruvboxYellow" },
        NavicIconsMethod = { link = "GruvboxBlue" },
        NavicIconsProperty = { link = "GruvboxAqua" },
        NavicIconsField = { link = "GruvboxPurple" },
        NavicIconsConstructor = { link = "GruvboxBlue" },
        NavicIconsEnum = { link = "GruvboxPurple" },
        NavicIconsInterface = { link = "GruvboxGreen" },
        NavicIconsFunction = { link = "GruvboxBlue" },
        NavicIconsVariable = { link = "GruvboxPurple" },
        NavicIconsConstant = { link = "GruvboxOrange" },
        NavicIconsString = { link = "GruvboxGreen" },
        NavicIconsNumber = { link = "GruvboxOrange" },
        NavicIconsBoolean = { link = "GruvboxOrange" },
        NavicIconsArray = { link = "GruvboxOrange" },
        NavicIconsObject = { link = "GruvboxOrange" },
        NavicIconsKey = { link = "GruvboxAqua" },
        NavicIconsNull = { link = "GruvboxOrange" },
        NavicIconsEnumMember = { link = "GruvboxYellow" },
        NavicIconsStruct = { link = "GruvboxPurple" },
        NavicIconsEvent = { link = "GruvboxYellow" },
        NavicIconsOperator = { link = "GruvboxRed" },
        NavicIconsTypeParameter = { link = "GruvboxRed" },
        NavicText = { link = "GruvboxWhite" },
        NavicSeparator = { link = "GruvboxWhite" },

        -- LSPSaga
        LspSagaCodeActionTitle = { link = "Title" },
        LspSagaCodeActionBorder = { link = "GruvboxFg1" },
        LspSagaCodeActionContent = { fg = palette.green, bold = config.bold },
        LspSagaLspFinderBorder = { link = "GruvboxFg1" },
        LspSagaAutoPreview = { link = "GruvboxOrange" },
        TargetWord = { fg = palette.blue, bold = config.bold },
        FinderSeparator = { link = "GruvboxAqua" },
        LspSagaDefPreviewBorder = { link = "GruvboxBlue" },
        LspSagaHoverBorder = { link = "GruvboxOrange" },
        LspSagaRenameBorder = { link = "GruvboxBlue" },
        LspSagaDiagnosticSource = { link = "GruvboxOrange" },
        LspSagaDiagnosticBorder = { link = "GruvboxPurple" },
        LspSagaDiagnosticHeader = { link = "GruvboxGreen" },
        LspSagaSignatureHelpBorder = { link = "GruvboxGreen" },
        SagaShadow = { link = "GruvboxBg0" },

        -- Dashboard
        DashboardShortCut = { link = "GruvboxOrange" },
        DashboardHeader = { link = "GruvboxAqua" },
        DashboardCenter = { link = "GruvboxYellow" },
        DashboardFooter = { fg = palette.purple, italic = true },

        -- Mason
        MasonHighlight = { link = "GruvboxAqua" },
        MasonHighlightBlock = { fg = palette.bg0, bg = palette.blue },
        MasonHighlightBlockBold = { fg = palette.bg0, bg = palette.blue, bold = true },
        MasonHighlightSecondary = { fg = palette.yellow },
        MasonHighlightBlockSecondary = { fg = palette.bg0, bg = palette.yellow },
        MasonHighlightBlockBoldSecondary = { fg = palette.bg0, bg = palette.yellow, bold = true },
        MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
        MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
        MasonMuted = { fg = palette.fg4 },
        MasonMutedBlock = { fg = palette.bg0, bg = palette.fg4 },
        MasonMutedBlockBold = { fg = palette.bg0, bg = palette.fg4, bold = true },

        -- Carbon
        CarbonFile = { link = "GruvboxFg1" },
        CarbonExe = { link = "GruvboxYellow" },
        CarbonSymlink = { link = "GruvboxAqua" },
        CarbonBrokenSymlink = { link = "GruvboxRed" },
        CarbonIndicator = { link = "GruvboxGray" },
        CarbonDanger = { link = "GruvboxRed" },
        CarbonPending = { link = "GruvboxYellow" },

        -- Noice
        NoiceCursor = { link = "TermCursor" },
        NoiceCmdlinePopupBorder = { fg = palette.blue, bg = "NONE" },
        NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
        NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
        NoiceCmdlinePopupBorderSearch = { fg = palette.yellow, bg = "NONE" },
        NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },

        -- Notify
        NotifyDEBUGBorder = { link = "GruvboxBlue" },
        NotifyDEBUGIcon = { link = "GruvboxBlue" },
        NotifyDEBUGTitle = { link = "GruvboxBlue" },
        NotifyERRORBorder = { link = "GruvboxRed" },
        NotifyERRORIcon = { link = "GruvboxRed" },
        NotifyERRORTitle = { link = "GruvboxRed" },
        NotifyINFOBorder = { link = "GruvboxAqua" },
        NotifyINFOIcon = { link = "GruvboxAqua" },
        NotifyINFOTitle = { link = "GruvboxAqua" },
        NotifyTRACEBorder = { link = "GruvboxGreen" },
        NotifyTRACEIcon = { link = "GruvboxGreen" },
        NotifyTRACETitle = { link = "GruvboxGreen" },
        NotifyWARNBorder = { link = "GruvboxYellow" },
        NotifyWARNIcon = { link = "GruvboxYellow" },
        NotifyWARNTitle = { link = "GruvboxYellow" },

        -- Illuminate
        IlluminatedWordText = { link = "LspReferenceText" },
        IlluminatedWordRead = { link = "LspReferenceRead" },
        IlluminatedWordWrite = { link = "LspReferenceWrite" },

        -- Rainbow Delimiters
        RainbowDelimiterRed = { fg = palette.red },
        RainbowDelimiterOrange = { fg = palette.orange },
        RainbowDelimiterYellow = { fg = palette.yellow },
        RainbowDelimiterGreen = { fg = palette.green },
        RainbowDelimiterBlue = { fg = palette.blue },
        RainbowDelimiterViolet = { fg = palette.purple },
        RainbowDelimiterCyan = { fg = palette.aqua },

        -- DAP
        DapBreakpointSymbol = { fg = palette.red, bg = palette.bg1 },
        DapStoppedSymbol = { fg = palette.green, bg = palette.bg1 },
        DapUIBreakpointsCurrentLine = { link = "GruvboxYellow" },
        DapUIBreakpointsDisabledLine = { link = "GruvboxGray" },
        DapUIBreakpointsInfo = { link = "GruvboxAqua" },
        DapUIBreakpointsLine = { link = "GruvboxYellow" },
        DapUIBreakpointsPath = { link = "GruvboxBlue" },
        DapUICurrentFrameName = { link = "GruvboxPurple" },
        DapUIDecoration = { link = "GruvboxPurple" },
        DapUIEndofBuffer = { link = "EndOfBuffer" },
        DapUIFloatBorder = { link = "GruvboxAqua" },
        DapUILineNumber = { link = "GruvboxYellow" },
        DapUIModifiedValue = { link = "GruvboxRed" },
        DapUIPlayPause = { fg = palette.green, bg = palette.bg1 },
        DapUIRestart = { fg = palette.green, bg = palette.bg1 },
        DapUIScope = { link = "GruvboxBlue" },
        DapUISource = { link = "GruvboxFg1" },
        DapUIStepBack = { fg = palette.blue, bg = palette.bg1 },
        DapUIStepInto = { fg = palette.blue, bg = palette.bg1 },
        DapUIStepOut = { fg = palette.blue, bg = palette.bg1 },
        DapUIStepOver = { fg = palette.blue, bg = palette.bg1 },
        DapUIStop = { fg = palette.red, bg = palette.bg1 },
        DapUIStoppedThread = { link = "GruvboxBlue" },
        DapUIThread = { link = "GruvboxBlue" },
        DapUIType = { link = "GruvboxOrange" },
        DapUIUnavailable = { link = "GruvboxGray" },
        DapUIWatchesEmpty = { link = "GruvboxGray" },
        DapUIWatchesError = { link = "GruvboxRed" },
        DapUIWatchesValue = { link = "GruvboxYellow" },
        DapUIWinSelect = { link = "GruvboxYellow" },

        -- NeoGit
        NeogitDiffDelete = { link = "DiffDelete" },
        NeogitDiffAdd = { link = "DiffAdd" },
        NeogitHunkHeader = { link = "WinBar" },
        NeogitHunkHeaderHighlight = { link = "WinBarNC" },

        -- Diffview
        DiffviewStatusModified = { link = "GruvboxGreenBold" },
        DiffviewFilePanelInsertions = { link = "GruvboxGreenBold" },
        DiffviewFilePanelDeletions = { link = "GruvboxRedBold" },

        -- Mini.nvim
        MiniAnimateCursor = { reverse = true, nocombine = true },
        MiniAnimateNormalFloat = { fg = palette.fg1, bg = palette.bg1 },
        MiniClueBorder = { link = "FloatBorder" },
        MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
        MiniClueDescSingle = { link = "NormalFloat" },
        MiniClueNextKey = { link = "DiagnosticFloatingHint" },
        MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
        MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
        MiniClueTitle = { link = "FloatTitle" },
        MiniCompletionActiveParameter = { underline = true },
        MiniCursorword = { underline = true },
        MiniCursorwordCurrent = { underline = true },
        MiniDepsChangeAdded = { link = "GruvboxGreen" },
        MiniDepsChangeRemoved = { link = "GruvboxRed" },
        MiniDepsHint = { link = "DiagnosticHint" },
        MiniDepsInfo = { link = "DiagnosticInfo" },
        MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
        MiniDepsPlaceholder = { link = "Comment" },
        MiniDepsTitle = { link = "Title" },
        MiniDepsTitleError = { link = "DiffDelete" },
        MiniDepsTitleSame = { link = "DiffChange" },
        MiniDepsTitleUpdate = { link = "DiffAdd" },
        MiniDiffOverAdd = { link = "DiffAdd" },
        MiniDiffOverChange = { link = "DiffText" },
        MiniDiffOverContext = { link = "DiffChange" },
        MiniDiffOverDelete = { link = "DiffDelete" },
        MiniDiffSignAdd = { link = "GruvboxGreen" },
        MiniDiffSignChange = { link = "GruvboxAqua" },
        MiniDiffSignDelete = { link = "GruvboxRed" },
        MiniFilesBorder = { link = "FloatBorder" },
        MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
        MiniFilesCursorLine = { bg = palette.bg2 },
        MiniFilesDirectory = { link = "Directory" },
        MiniFilesFile = { link = "GruvboxFg1" },
        MiniFilesNormal = { link = "NormalFloat" },
        MiniFilesTitle = { link = "FloatTitle" },
        MiniFilesTitleFocused = { link = "GruvboxOrangeBold" },
        MiniHipatternsFixme = { fg = palette.bg0, bg = palette.red, bold = config.bold },
        MiniHipatternsHack = { fg = palette.bg0, bg = palette.yellow, bold = config.bold },
        MiniHipatternsNote = { fg = palette.bg0, bg = palette.blue, bold = config.bold },
        MiniHipatternsTodo = { fg = palette.bg0, bg = palette.aqua, bold = config.bold },
        MiniIconsAzure = { link = "GruvboxBlue" },
        MiniIconsBlue = { link = "GruvboxBlue" },
        MiniIconsCyan = { link = "GruvboxAqua" },
        MiniIconsGreen = { link = "GruvboxGreen" },
        MiniIconsGrey = { link = "GruvboxFg0" },
        MiniIconsOrange = { link = "GruvboxOrange" },
        MiniIconsPurple = { link = "GruvboxPurple" },
        MiniIconsRed = { link = "GruvboxRed" },
        MiniIconsYellow = { link = "GruvboxYellow" },
        MiniIndentscopeSymbol = { link = "GruvboxGray" },
        MiniIndentscopeSymbolOff = { link = "GruvboxYellow" },
        MiniJump = { link = "GruvboxOrangeUnderline" },
        MiniJump2dDim = { link = "GruvboxGray" },
        MiniJump2dSpot = { fg = palette.orange, bold = config.bold, nocombine = true },
        MiniJump2dSpotAhead = { fg = palette.aqua, bg = palette.bg0, nocombine = true },
        MiniJump2dSpotUnique = { fg = palette.yellow, bold = config.bold, nocombine = true },
        MiniMapNormal = { link = "NormalFloat" },
        MiniMapSymbolCount = { link = "Special" },
        MiniMapSymbolLine = { link = "Title" },
        MiniMapSymbolView = { link = "Delimiter" },
        MiniNotifyBorder = { link = "FloatBorder" },
        MiniNotifyNormal = { link = "NormalFloat" },
        MiniNotifyTitle = { link = "FloatTitle" },
        MiniOperatorsExchangeFrom = { link = "IncSearch" },
        MiniPickBorder = { link = "FloatBorder" },
        MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
        MiniPickBorderText = { link = "FloatTitle" },
        MiniPickIconDirectory = { link = "Directory" },
        MiniPickIconFile = { link = "MiniPickNormal" },
        MiniPickHeader = { link = "DiagnosticFloatingHint" },
        MiniPickMatchCurrent = { bg = palette.bg2 },
        MiniPickMatchMarked = { link = "Visual" },
        MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
        MiniPickNormal = { link = "NormalFloat" },
        MiniPickPreviewLine = { link = "CursorLine" },
        MiniPickPreviewRegion = { link = "IncSearch" },
        MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
        MiniStarterCurrent = { nocombine = true },
        MiniStarterFooter = { link = "GruvboxGray" },
        MiniStarterHeader = { link = "Title" },
        MiniStarterInactive = { link = "Comment" },
        MiniStarterItem = { link = "Normal" },
        MiniStarterItemBullet = { link = "Delimiter" },
        MiniStarterItemPrefix = { link = "WarningMsg" },
        MiniStarterSection = { link = "Delimiter" },
        MiniStarterQuery = { link = "MoreMsg" },
        MiniStatuslineDevinfo = { link = "StatusLine" },
        MiniStatuslineFileinfo = { link = "StatusLine" },
        MiniStatuslineFilename = { link = "StatusLineNC" },
        MiniStatuslineInactive = { link = "StatusLineNC" },
        MiniStatuslineModeCommand = { fg = palette.bg0, bg = palette.yellow, bold = config.bold },
        MiniStatuslineModeInsert = { fg = palette.bg0, bg = palette.blue, bold = config.bold },
        MiniStatuslineModeNormal = { fg = palette.bg0, bg = palette.fg1, bold = config.bold },
        MiniStatuslineModeOther = { fg = palette.bg0, bg = palette.aqua, bold = config.bold },
        MiniStatuslineModeReplace = { fg = palette.bg0, bg = palette.red, bold = config.bold },
        MiniStatuslineModeVisual = { fg = palette.bg0, bg = palette.green, bold = config.bold },
        MiniSurround = { link = "IncSearch" },
        MiniTablineCurrent = {
            fg = palette.green,
            bg = palette.bg1,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineFill = { link = "TabLineFill" },
        MiniTablineHidden = { fg = palette.bg4, bg = palette.bg1, reverse = config.invert_tabline },
        MiniTablineModifiedCurrent = {
            fg = palette.bg1,
            bg = palette.green,
            bold = config.bold,
            reverse = config.invert_tabline,
        },
        MiniTablineModifiedHidden = { fg = palette.bg1, bg = palette.bg4, reverse = config.invert_tabline },
        MiniTablineModifiedVisible = { fg = palette.bg1, bg = palette.fg1, reverse = config.invert_tabline },
        MiniTablineTabpagesection = { link = "Search" },
        MiniTablineVisible = { fg = palette.fg1, bg = palette.bg1, reverse = config.invert_tabline },
        MiniTestEmphasis = { bold = config.bold },
        MiniTestFail = { link = "GruvboxRedBold" },
        MiniTestPass = { link = "GruvboxGreenBold" },
        MiniTrailspace = { bg = palette.red },

        -- Neo-Tree
        NeoTreeFloatTitle = { link = "FloatTitle" },
        NeoTreeFloatNormal = { fg = palette.fg1, bg = palette.bg0 },
        NeoTreeFloatBorder = { fg = palette.bg3, bg = palette.bg0 },
        NeoTreeTitleBar = { fg = palette.bg0, bg = palette.bg3 },
        NeoTreeBufferNumber = { fg = palette.orange },
        NeoTreeMessage = { fg = palette.gray, italic = true },
        NeoTreeDimText = { fg = palette.gray },
        NeoTreeDirectoryIcon = { fg = palette.blue },
        NeoTreeDirectoryName = { fg = palette.fg1 },
        NeoTreeDotfile = { fg = palette.gray },
        NeoTreeHiddenByName = { fg = palette.gray },
        NeoTreeFadeText1 = { fg = palette.bg3 },
        NeoTreeFadeText2 = { fg = palette.bg2 },
        NeoTreeFileIcon = { fg = palette.blue },
        NeoTreeIndentMarker = { fg = palette.bg2 },
        NeoTreeExpander = { fg = palette.bg4 },
        NeoTreeModified = { fg = palette.yellow },
        NeoTreeGitAdded = { fg = palette.green },
        NeoTreeGitDeleted = { fg = palette.red },
        NeoTreeGitModified = { fg = palette.orange },
        NeoTreeGitConflict = { fg = palette.yellow, italic = true, bold = true },
        NeoTreeGitUntracked = { fg = palette.purple, italic = true },
        NeoTreeTabInactive = { fg = palette.gray },
        NeoTreeTabSeparatorActive = { bg = palette.bg1, fg = palette.blue },
        NeoTreeTabSeparatorInactive = { bg = palette.bg0, fg = palette.gray },
        NeoTreeFileStats = { fg = palette.bg3 },
        NeoTreeFileStatsHeader = { fg = palette.bg4, bold = true },

        -- Treesitter
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { link = "GruvboxRed" },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { link = "GruvboxFg1" },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@markup"] = { link = "GruvboxFg1" },
        ["@markup.strong"] = { bold = config.bold },
        ["@markup.italic"] = { link = "@text.emphasis" },
        ["@markup.underline"] = { underline = config.underline },
        ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.math"] = { link = "Special" },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { link = "Type" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { link = "GruvboxGreen" },
        ["@markup.list.unchecked"] = { link = "GruvboxGray" },
        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "SpecialComment" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },
        ["@diff.plus"] = { link = "diffAdded" },
        ["@diff.minus"] = { link = "diffRemoved" },
        ["@diff.delta"] = { link = "diffChanged" },
        ["@module"] = { link = "GruvboxFg1" },
        ["@namespace"] = { link = "GruvboxFg1" },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { link = "GruvboxFg1" },
        ["@text.strong"] = { bold = config.bold },
        ["@text.emphasis"] = { italic = config.italic.emphasis },
        ["@text.underline"] = { underline = config.underline },
        ["@text.strike"] = { strikethrough = config.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { link = "GruvboxGreen" },
        ["@text.todo.unchecked"] = { link = "GruvboxGray" },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = palette.purple, bold = config.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = { fg = palette.fg0, bg = palette.red, bold = config.bold },
        ["@text.diff.add"] = { link = "diffAdded" },
        ["@text.diff.delete"] = { link = "diffRemoved" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },

        -- Semantic Tokens
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.variable"] = { link = "@variable" },
    }

    if config.override then
        for hl, content in pairs(config.override) do
            groups[hl] = content
        end
    end

    return groups
end

return M
