local p = require("gruvbox.colors").palette

---@class GruvboxLight
return {
    bg0 = p.light0,
    bg1 = p.light1,
    bg2 = p.light2,
    bg3 = p.light3,
    bg4 = p.light4,
    fg0 = p.dark0,
    fg1 = p.dark1,
    fg2 = p.dark2,
    fg3 = p.dark3,
    fg4 = p.dark4,
    red = p.faded_red,
    green = p.faded_green,
    yellow = p.faded_yellow,
    blue = p.faded_blue,
    purple = p.faded_purple,
    aqua = p.faded_aqua,
    orange = p.faded_orange,
    neutral_red = p.neutral_red,
    neutral_green = p.neutral_green,
    neutral_yellow = p.neutral_yellow,
    neutral_blue = p.neutral_blue,
    neutral_purple = p.neutral_purple,
    neutral_aqua = p.neutral_aqua,
    dark_red = p.light_red,
    dark_green = p.light_green,
    dark_aqua = p.light_aqua,
    gray = p.gray,
}
